'use client';

import { Suspense, useRef, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { Anton } from 'next/font/google';
import { usePreviewImage } from '@/lib/design/use-preview-image';

const anton = Anton({ subsets: ['latin'], weight: '400', display: 'swap' });

const SIZES = ['S', 'M', 'L', 'XL', 'XXL'];

// Gildan Heavy Cotton 5000 spec sheet, in cm.
const SIZE_MEASUREMENTS: Record<string, { chest: number; length: number }> = {
  S: { chest: 91, length: 71 },
  M: { chest: 102, length: 74 },
  L: { chest: 112, length: 76 },
  XL: { chest: 122, length: 79 },
  XXL: { chest: 132, length: 81 },
};

function TshirtContent() {
  const searchParams = useSearchParams();

  const pain = searchParams.get('pain') || '';
  const viande = searchParams.get('viande') || '';
  const cruditesRaw = searchParams.get('crudites') || '';
  const saucesRaw = searchParams.get('sauces') || '';

  const crudites = cruditesRaw ? cruditesRaw.split(',') : [];
  const sauces = saucesRaw ? saucesRaw.split(',') : [];

  const [selectedSize, setSelectedSize] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const sizeGuideRef = useRef<HTMLDialogElement>(null);

  const openSizeGuide = () => sizeGuideRef.current?.showModal();
  const closeSizeGuide = () => sizeGuideRef.current?.close();

  // Same query shape /api/design and /api/checkout both consume — the image
  // rendered here for preview is generated by the exact same engine and the
  // exact same inputs as the file that will be sent to Printful. There is no
  // separate client-side rendering path left to drift out of sync.
  const designParams = new URLSearchParams();
  if (pain) designParams.set('pain', pain);
  if (viande) designParams.set('viande', viande);
  if (crudites.length) designParams.set('crudites', crudites.join(','));
  if (sauces.length) designParams.set('sauces', sauces.join(','));
  const designQuery = designParams.toString();
  const designSrc = `/api/design?${designQuery}`;
  // Same params as designSrc — carries the exact selection back to "/" so
  // the URL-sync effect there (see app/page.tsx) can restore it, instead of
  // resetting to a blank configuration.
  const backHref = `/?${designQuery}`;

  // 'design' variant — a distinct cache namespace from the home borne's
  // 'PREVIEW_FORMAT' (share) previews, since this is a different endpoint
  // producing a different (full print-size) image. If the home page's own
  // preload already warmed this exact combination (or the browser's HTTP
  // cache still has it from the last time this page itself fetched it),
  // this renders instantly instead of showing a blank chest for ~1.3s.
  const previewSrc = usePreviewImage(designSrc, { pain, viande, crudites, sauces }, 'design');

  const handleCommander = async () => {
    setError('');
    if (!selectedSize) {
      setError('Choisis une taille avant de commander.');
      return;
    }
    setLoading(true);
    try {
      const res = await fetch('/api/checkout', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          size: selectedSize,
          bread: pain,
          meat: viande,
          vegetables: crudites,
          sauces,
        }),
      });
      const data = await res.json();
      if (data.url) {
        window.location.href = data.url;
      } else {
        setError(data.error || 'Une erreur est survenue.');
        setLoading(false);
      }
    } catch {
      setError('Impossible de contacter le serveur.');
      setLoading(false);
    }
  };

  return (
    <main className={`page ${anton.className}`}>
      <header className="topBar">
        <Link href={backHref} className="backLink">
          ← RETOUR
        </Link>
        <h1>TON T-SHIRT</h1>
        <div className="spacer" />
      </header>

      <div className="content">
        <div className="productZone">
          <div className="tshirtFrame">
            <div className="tshirtContainer">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src="/tshirt-base.png" alt="T-shirt mockup" className="tshirtImg" />
              {/* Same PNG, same engine, same query params as the file sent to
                  Printful — this is a direct preview of the real print file,
                  not a separate approximation. previewSrc (not designSrc
                  directly) so a combination already cached this session
                  (e.g. preloaded from the home page) shows immediately
                  instead of leaving a blank chest while /api/design loads. */}
              {previewSrc && (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={previewSrc} alt="Aperçu de ton design" className="chestDesign" />
              )}
            </div>
          </div>
        </div>

        <div className="purchasePanel">
          <div className="panelHeader">
            <span className="productName">T-SHIRT NOIR</span>
            <span className="productPrice">29,99&nbsp;€</span>
          </div>
          <p className="productDesc">Impression premium · Créé à la demande</p>

          <div className="sizeSection">
            <div className="sizeSectionHeader">
              <span className="sizeLabel">TAILLE</span>
              <button type="button" className="sizeGuideLink" onClick={openSizeGuide}>
                Guide des tailles
              </button>
            </div>
            <div className="sizeButtons">
              {SIZES.map((size) => (
                <button
                  key={size}
                  type="button"
                  className={`sizeBtn${selectedSize === size ? ' active' : ''}`}
                  onClick={() => setSelectedSize(size)}
                >
                  {size}
                </button>
              ))}
            </div>
          </div>

          <button type="button" className="commanderBtn" onClick={handleCommander} disabled={loading}>
            {loading ? '...' : 'COMMANDER'}
          </button>

          {error && <div className="paymentMsg errorMsg">{error}</div>}

          <div className="orderInfo">
            <span className="orderInfoMain">Livraison incluse</span>
            <span className="orderInfoSub">Chaque t-shirt est imprimé spécialement pour toi.</span>
          </div>
        </div>
      </div>

      <dialog
        ref={sizeGuideRef}
        className="sizeGuideDialog"
        onClick={(e) => {
          if (e.target === e.currentTarget) sizeGuideRef.current?.close();
        }}
        onKeyDown={(e) => {
          if (e.key === 'Escape') sizeGuideRef.current?.close();
        }}
      >
        <div className="sizeGuideInner">
          <div className="sizeGuideHeaderRow">
            <span className="sizeGuideTitle">GUIDE DES TAILLES</span>
            <button type="button" className="sizeGuideClose" onClick={closeSizeGuide} aria-label="Fermer">
              ×
            </button>
          </div>
          <table className="sizeGuideTable">
            <thead>
              <tr>
                <th></th>
                {SIZES.map((size) => (
                  <th key={size}>{size}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Tour de poitrine</td>
                {SIZES.map((size) => (
                  <td key={size}>{SIZE_MEASUREMENTS[size].chest}</td>
                ))}
              </tr>
              <tr>
                <td>Hauteur</td>
                {SIZES.map((size) => (
                  <td key={size}>{SIZE_MEASUREMENTS[size].length}</td>
                ))}
              </tr>
            </tbody>
          </table>
          <p className="sizeGuideNote">Mesures en cm. Tolérance de fabrication : ± 2 cm.</p>
        </div>
      </dialog>

      <style jsx>{`
        .page {
          min-height: 100vh;
          background: #000;
          color: #fff;
          display: flex;
          flex-direction: column;
          padding: 20px 24px 24px;
          box-sizing: border-box;
          position: relative;
        }

        .topBar {
          display: flex;
          align-items: center;
          justify-content: space-between;
          margin-bottom: 16px;
        }

        .backLink {
          color: #fff;
          text-decoration: none;
          font-size: 0.88rem;
          letter-spacing: 0.12em;
          opacity: 0.72;
          transition: opacity 0.2s;
          white-space: nowrap;
          min-width: 80px;
        }

        .backLink:hover {
          opacity: 1;
        }

        h1 {
          margin: 0;
          font-size: clamp(2rem, 5vw, 3.5rem);
          letter-spacing: 0.16em;
          text-align: center;
          flex: 1;
        }

        .spacer {
          min-width: 80px;
        }

        .content {
          flex: 1;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          gap: 20px;
          width: 100%;
        }

        .productZone {
          width: 100%;
          display: flex;
          justify-content: center;
        }

        .tshirtFrame {
          background: #fff;
          padding: 16px;
          width: 100%;
          max-width: 520px;
          aspect-ratio: 1;
          display: flex;
          align-items: center;
          justify-content: center;
          box-sizing: border-box;
        }

        .tshirtContainer {
          position: relative;
          width: 100%;
        }

        .tshirtImg {
          width: 100%;
          height: auto;
          display: block;
        }

        .chestDesign {
          /* Iterating from the 35%/36% pass per visual feedback ("plus bas,
             et plus gros") — center-anchored (matches renderDesign()
             centering text within its own canvas, lib/design/render.ts) so
             this holds regardless of order length. */
          position: absolute;
          top: 44%;
          left: 50%;
          transform: translate(-50%, -50%);
          width: 44%;
          height: auto;
          display: block;
        }

        .purchasePanel {
          width: 100%;
          max-width: 420px;
          background: #050505;
          border: 1px solid #666;
          border-radius: 18px;
          padding: 22px;
          box-sizing: border-box;
          display: flex;
          flex-direction: column;
          gap: 14px;
        }

        .panelHeader {
          display: flex;
          align-items: baseline;
          justify-content: space-between;
          gap: 12px;
        }

        .productName {
          font-size: 1rem;
          letter-spacing: 0.08em;
          opacity: 0.92;
        }

        .productPrice {
          font-size: 1.2rem;
          letter-spacing: 0.04em;
          white-space: nowrap;
        }

        .productDesc {
          margin: -6px 0 0;
          font-size: 0.76rem;
          letter-spacing: 0.04em;
          opacity: 0.5;
        }

        .sizeSection {
          display: flex;
          flex-direction: column;
          gap: 10px;
          margin-top: 4px;
        }

        .sizeSectionHeader {
          display: flex;
          align-items: center;
          justify-content: space-between;
        }

        .sizeLabel {
          font-size: 0.78rem;
          letter-spacing: 0.18em;
          opacity: 0.6;
        }

        .sizeGuideLink {
          background: none;
          border: none;
          padding: 0;
          margin: 0;
          color: #fff;
          opacity: 0.55;
          font-size: 0.72rem;
          letter-spacing: 0.03em;
          text-decoration: underline;
          text-underline-offset: 2px;
          cursor: pointer;
          font-family: inherit;
          transition: opacity 0.2s ease;
        }

        .sizeGuideLink:hover {
          opacity: 0.9;
        }

        .sizeButtons {
          display: flex;
          gap: 8px;
        }

        .sizeBtn {
          flex: 1;
          height: 44px;
          border: 1px solid #666;
          background: #000;
          color: #fff;
          font-weight: 700;
          font-size: 0.85rem;
          letter-spacing: 0.08em;
          text-transform: uppercase;
          cursor: pointer;
          transition: background 0.2s ease, color 0.2s ease, border-color 0.2s ease;
          font-family: inherit;
        }

        .sizeBtn:hover {
          border-color: #999;
        }

        .sizeBtn.active {
          background: #fff;
          color: #000;
          border-color: #fff;
        }

        .commanderBtn {
          width: 100%;
          height: 56px;
          border: 1px solid #fff;
          background: #fff;
          color: #000;
          font-weight: 700;
          font-size: 0.92rem;
          letter-spacing: 0.08em;
          text-transform: uppercase;
          cursor: pointer;
          transition: background 0.2s ease, color 0.2s ease;
          font-family: inherit;
        }

        .commanderBtn:hover {
          background: #e0e0e0;
        }

        .commanderBtn:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .paymentMsg {
          text-align: center;
          font-size: 0.82rem;
          letter-spacing: 0.06em;
          opacity: 0.55;
          padding: 4px 0;
        }

        .errorMsg {
          opacity: 1;
          color: #ff6b6b;
        }

        .orderInfo {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 4px;
          padding: 2px 0 0;
          text-align: center;
        }

        .orderInfoMain {
          font-size: 0.82rem;
          letter-spacing: 0.08em;
          opacity: 0.75;
        }

        .orderInfoSub {
          font-size: 0.72rem;
          letter-spacing: 0.05em;
          opacity: 0.45;
        }

        .sizeGuideDialog {
          margin: auto;
          background: #000;
          color: #fff;
          border: 1px solid #666;
          border-radius: 12px;
          padding: 0;
          width: min(420px, 92vw);
        }

        :global(dialog.sizeGuideDialog::backdrop) {
          background: rgba(0, 0, 0, 0.7);
        }

        .sizeGuideInner {
          display: flex;
          flex-direction: column;
          gap: 14px;
          padding: 20px;
          box-sizing: border-box;
          max-height: 80vh;
          overflow-y: auto;
        }

        .sizeGuideHeaderRow {
          display: flex;
          align-items: center;
          justify-content: space-between;
        }

        .sizeGuideTitle {
          font-size: 0.92rem;
          letter-spacing: 0.12em;
        }

        .sizeGuideClose {
          background: none;
          border: none;
          color: #fff;
          font-size: 1.5rem;
          line-height: 1;
          opacity: 0.7;
          cursor: pointer;
          font-family: inherit;
          padding: 0;
          outline: none;
          box-shadow: none;
        }

        .sizeGuideClose:hover,
        .sizeGuideClose:focus,
        .sizeGuideClose:focus-visible {
          opacity: 1;
          outline: none;
          box-shadow: none;
        }

        .sizeGuideTable {
          width: 100%;
          border-collapse: collapse;
          font-size: 0.8rem;
          table-layout: fixed;
        }

        .sizeGuideTable th,
        .sizeGuideTable td {
          border: 1px solid #333;
          padding: 10px 4px;
          text-align: center;
        }

        .sizeGuideTable th:first-child,
        .sizeGuideTable td:first-child {
          text-align: left;
          padding-left: 8px;
        }

        .sizeGuideTable th {
          opacity: 0.7;
          letter-spacing: 0.03em;
        }

        .sizeGuideTable td {
          opacity: 0.9;
        }

        .sizeGuideNote {
          margin: 0;
          font-size: 0.72rem;
          letter-spacing: 0.02em;
          opacity: 0.5;
          line-height: 1.5;
        }

        /* ── Desktop: side-by-side, mockup grows, panel stays a compact
             bordered card — no forced equal-height stretch, each column
             centers at its own natural height. ── */
        @media (min-width: 601px) {
          .content {
            flex-direction: row;
            align-items: center;
            justify-content: center;
            gap: 56px;
            max-width: 1180px;
            margin: 0 auto;
          }

          .productZone {
            flex: 1.15;
            max-width: 640px;
          }

          .tshirtFrame {
            max-width: 100%;
          }

          .purchasePanel {
            flex: 0 0 380px;
            max-width: 420px;
          }
        }

        /* ── Mobile ── */
        @media (max-width: 600px) {
          .page {
            padding: 14px 12px 88px;
          }

          /* True viewport-relative centering: the title is taken out of
             flow and centered on .topBar itself, independent of how wide
             "← RETOUR" is — no flanking spacer needs to match its width. */
          .topBar {
            position: relative;
            min-height: 40px;
            margin-bottom: 12px;
          }

          .backLink {
            position: relative;
            z-index: 1;
            min-width: 0;
          }

          h1 {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            flex: none;
            margin: 0;
            white-space: nowrap;
            font-size: clamp(1.05rem, 5.5vw, 1.5rem);
          }

          .spacer {
            display: none;
          }

          .tshirtFrame {
            max-width: 520px;
          }

          .purchasePanel {
            max-width: 100%;
          }

          .commanderBtn {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            z-index: 50;
            border-left: none;
            border-right: none;
            border-bottom: none;
            height: 60px;
            font-size: 1rem;
          }
        }
      `}</style>
    </main>
  );
}

export default function TshirtPage() {
  return (
    <Suspense fallback={<div style={{ background: '#000', minHeight: '100vh' }} />}>
      <TshirtContent />
    </Suspense>
  );
}
